= Repasse da reunião aberta do Baixo Matão (06/03)
// :page-subtitle:
:page-identificador: 20240405_repasse_reuniao_aberta_bm
:page-data: "05 de abril de 2024"
:page-layout: boletim_post
:page-categories: [boletim_post]
:page-tags: []
:page-autoria: 'CAMat, Cefisma, Cepege, CAP e CAIAG'
// :page-autoria-completa: ''
:page-resumo: ['Breve repasse sobre a reunião com representantes do GT Mobilidade do Plano Diretor.']

No dia 06 de março, representantes dos CAs do Baixo Matão, representantes do Grupo de Trabalho Mobilidade do Plano Diretor e alguns estudantes se reuniram próximo ao bandejão da física para socializar acúmulos deste processo de reformulação do plano diretor do campus Butantã. A discussão foi motivada pela tentativa da prefeitura do campus em implementar o circular 04 imediatamente no período de volta às aulas, e a proposta colocada representava um isolamento da Rua do Matão, visto que os estudantes teriam de ir para o ponto da Av. Prof. Luciano Gualberto para pegarem um ônibus sentido Metrô Butantã.

Ainda que esta tenha sido a motivação, o momento de debate evidenciou o interesse da universidade em colocar em pauta os eixos políticos da mobilidade urbana no campus. Se o movimento estudantil ainda está centrado em exigir aumento de verba e frota para os circulares, os representantes do GT Mobilidade demonstram a intenção de trazer a tona questionamentos sobre o pleno acesso ao campus (sem grades, nem catracas), a possibilidade de mais linhas de ônibus da SPTrans circularem pela USP, aprimoração para circulação de pedestres e ciclistas, etc.

É nítido o descompasso entre os acúmulos do movimento estudantil e os anseios da universidade para a reformulação do Plano Diretor. Isto não deve ser um fator de paralisia do nosso movimento, mas sim um convite para estudarmos a fundo a questão de mobilidade urbana - o BoletIME #7 traz alguns apontamentos - e nos organizarmos para garantir nossa presença neste espaço e manter a defesa de nossas ideias nas oficinas do Plano Diretor que acontecerão ao longo deste ano.

A primeira oficina está agendada para o dia 11 de abril, na FAUD, às 18h.