= Em solidariedade aos estudantes perseguidos politicamente
// :page-subtitle:
:page-identificador: 20240406_solidariedade_estudantes_perseguidos_politicamente
:page-data: "04 de abril de 2024"
:page-layout: boletim_post
:page-categories: [boletim_post]
:page-tags: []
:page-autoria: 'CAMat, Cefisma, Cepege, CAP e CAIAG'
// :page-autoria-completa: ''
:page-resumo: ['Nota política dos centros acadêmicos do Baixo Matão acerca dos processos administrativos aplicados contra os estudantes do curso de ciências moleculares e o membro do ESPP.']

O curso de ciências moleculares (CM), ou “curso secreto”, se diferencia das demais graduações da USP devido ao ingresso se dar quando o estudante já está matriculado na universidade - não há como ingressar diretamente via FUVEST, ENEM ou SiSU. Outra diferença é não existir um “Instituto de Ciências Moleculares”, a sede do curso fica localizada no prédio InovaUSP: uma incubadora de startups e agregadora de iniciativas do capital financeiro e tecnológico, sendo uma ponte para as empresas privadas terem acesso direto as pesquisas acadêmicas mais recentes. Ainda, ao lado do InovaUSP, temos o Centro de Difusão Internacional (CDI), que, dentre outras coisas, organiza espaços fixos de apresentação de diferentes nações e uma forma de estreitar laços com esses países, visando colaboração técnico-científica: esses locais são os chamados “corner”, sendo um deles o “Israel Corner”.

Agora, tendo feita esta contextualização para que se entenda a dinâmica do curso de ciências moleculares, vamos aos fatos. 

No dia 16 de outubro de 2023, auge da greve de 2023, estudantes da gestão “Nem Ciência sem Política, nem Política sem Ciência” do Centro Acadêmico Favo 22 (entidade representativa dos estudantes do CM) foram destituídos de seu mandato mediante acusações de antissemitismo e promoção de grupos terroristas. Tal destituição se deu sob o pretexto de que, ao defender que as forças militares israelenses cometem genocídio contra o povo palestino, o representante do grupo Estudantes em Solidariedade ao Povo Palestino (ESPP), convidado pela gestão para a assembleia de curso, estaria reproduzindo um discurso de ódio contra o povo judeu.

Importante ressaltar que não há equivalência alguma entre antissemitismo e antissionismo, visto que o primeiro se trata de um ódio direcionado a um grupo étnico (semitas) e o segundo é direcionado a um projeto político. Inclusive, tal associação é desrespeitosa tanto para as vítimas do projeto sionista quanto para aqueles semitas antissionistas (que sim, existem). A partir desses espantalhos e de acusações de “impedimento de atividades acadêmicas”, foram realizados Processos Administrativos Disciplinares por parte da reitoria visando promover uma perseguição política de estudantes do CM e do membro do ESPP.

Os processos estão sendo conduzidos conforme o Regime Disciplinar da USP, instaurado na época da Ditadura Militar com o objetivo de reprimir toda e qualquer atividade política realizada no âmbito universitário, por docentes, funcionários e estudantis, bem como cerceando o direito a auto-organização dessas categorias.

Assim, devemos compreender esta ação da Universidade de São Paulo enquanto mais uma perseguição política - e em um momento de alta da mobilização dos estudantes no curso - tendo em vista dar consequência aos interesses sionistas na Universidade, que ainda mantém vários laços institucionais com Israel, como o Israel Corner e intercâmbios acadêmico, além de atender os interesses imediatos da Reitoria de sufocar a greve estudantil crescente naquele momento.

Relembremos que outra vez, em 2022, houve sanções disciplinares aplicadas aos estudantes, desta mesma gestão, devido a suas manifestações no InovaUSP frente ao descanso da política de permanência.

Cabe se perguntar: se a USP realmente se indigna com discursos de ódio, onde ela estava quando foram feitas pichações nazistas no Conjunto Residencial e na sede do DCE Livre da USP? Por que o silêncio quando um grupo de extrema-direita apareceu armado na FFLCH? Se a USP se importa tanto com o conforto e o bem-estar de seus estudantes, por que os ameaçou de jubilamento no ano passado (com a Circular 005/2023 da Pró-Reitoria de Graduação)? Quão honesta é a diplomação póstuma de estudantes mortos pela ditadura quando se persegue estudantes vivos com base no Regime Disciplinar da ditadura?

A USP demonstra nitidamente com esses ataques que a sua indignação com o suposto discurso de ódio é uma hipocrisia voltada a defender os interesses do sionismo e do capital financeiro frente ao movimento global em defesa do povo palestino e ao revigoramento do movimento estudantil com a greve no ano passado.