= Resposta ao professor Joel Barbujiani Sigolo
// :page-subtitle:
:page-identificador: 20240401_resposta_ao_prof_joel_sigolo
:page-data: "01 de abril de 2024"
:page-layout: boletim_post
:page-categories: [boletim_post]
:page-tags: []
:page-autoria: 'CAMat, Cefisma, Cepege, CAP e CAIAG'
// :page-autoria-completa: ''
:page-resumo: ['Carta dos centros acadêmicos do Baixo Matão ao professor Joel Barbujiani Sigolo como resposta à sua retratação enviada no dia 22 de março de 2024. Logo em seguida, há a carta enviada pelo professor para a ciência de todes estudantes do BM.']

[.aviso-amarelo]
--
Este texto é uma resposta à carta enviada pelo professor Joel Barbujiani Sigolo à representação estudantil do CEPEGE e do Baixo Matão. Trata-se da resposta do professor à carta de repúdio dos estudantes da turma 66 veículada, no dia 19 de março, pelos centros acadêmicos do Baixo Matão. A carta do professor se encontra ao final de nossa carta de resposta.
--

São Paulo, 01 de abril de 2024

Em nome do corpo estudantil Baixo-Matão, dedicamos esta carta ao professor Joel Barbujiani Sigolo como resposta à sua retratação enviada no dia 22 de março de 2024.

É de extremo pesar e terror entender que, segundo a carta-resposta do professor, nunca foi sequer hipotetizado pelo mesmo que, de alguma maneira, expor uma estudante diante de uma turma inteira como “pior aluno da turma” poderia trazer mínimo desconforto ou constrangimento à pessoa ao apresentar, num tom desdenhoso, que não houve “intenção de magoar ou vilipendiar a estudante ou seus colegas”.

Um ato de humilhação em público continua sendo humilhação em público independentemente da resposta da vítima - seja de denúncia, ou manter-se calada -. Assim, numa análise do incidente em si seguindo os relatos da turma, fica evidente que o pesar e terror presumida inicialmente nesta presente carta não condiz com a realidade. Durante o incidente, o professor afirmou que leria para a sala ele mesmo o livro - prêmio para o “pior aluno da turma” - pois “ela [a estudante] está envergonhada”. Entendemos, portanto, que não houve honestidade intelectual nem sinceridade no pedido de desculpas do professor, uma vez que o ato foi claramente intencionado ao constrangimento e humilhação - ainda mais considerando que existe um histórico longilíneo de assédios em sala de aula conduzido pelo professor -. Erros não podem e não devem ser relativizados, desta forma, repudiamos, além do ato do assédio, a negação e a tentativa de se justificar do professor Joel Barbujiani Sigolo.

Representando o Baixo-Matão enquanto entidades, reconhecemos que existe um plano de discussão completamente ignorado deste incidente: o plano do racismo. Dizer somente que houve “uso jocoso do idioma de seus ancestrais” é ignorar a gravidade que é o uso de maneira únicamente intencionado ao constrangimento através do emprego preconceituoso e excludente das expressões de uma linguagem estrangeira, possivelmente sem sequer entender o significado destas.

Ao efetuar o ato de vocalizar indiscriminadamente essas expressões baseado somente na aparência da estudante - sem reconhecer de fato a maneira como esta se identifica -, a coloca num lugar de Outra - ela é diferente de nós, ela não faz parte de quem somos -. Além disso, o ato reduz uma cultura milenar, repleto de nuances, em simples palavras pronunciadas de maneira errada e sem significado, contribuindo para uma construção de sentido que torna esta cultura como inferior, não civilizada. Assim, fica evidente a importância de entender que estas expressões surgem, inicialmente, através de motivações e processos racistas e anti-migratórias, e a sua perpetuação nos tempos modernos reforça a estrutura racista.

Desta maneira, concluímos a presente carta novamente prestando solidariedade à vítima e denunciando a sequência de má-condutas do professor Joel Barbujiani Sigolo, como também realizando uma autocrítica da nossa conduta enquanto Baixo-Matão ao ignorar a dimensão do racismo durante o incidente.

Atenciosamente,

Centro Acadêmico do IAG - Gestão Vivenciage

Centro Acadêmico da Física USP - Gestão Quebra de Simetria

Centro Paulista de Estudos Geológicos - Gestão Chapa da Diamantina

Centro Acadêmico da Matemática, Estatística e Computação - Gestão Alexandra Elbakyan

Centro Acadêmico Panthalassa - Gestão Maré Vermelha

---

== À representação estudantil do CEPEGE e representação estudantil do Baixo Matão (Joel)

São Paulo, 22 de março de 2024

Apresentei no dia 20 do corrente mês meu pedido de sinceras desculpas pessoais para a aluna Beatriz na presença dos alunos da turma 66, foco principal desse episódio e estendo a todos os estudantes representados pelos coletivos aqui endereçados.

A entrega à a estudante de um livro de poesias como forma de premiação negativa em relação a sua performance acadêmica foi de minha parte uma atitude equivocada e muito mas muito infeliz além de mal colocada de minha parte que gerou constrangimento para ela e para os colegas presentes.

Compreendo o mau tom de minha atitude despropositada tanto em relação à premiação como em relação ao uso de expressões idiomáticas vinculadas a origem ancestral da referida aluna e assumo integral responsabilidade por esse ato indubitavelmente infeliz ao extremo e despropositado.

Em momento nenhum tive intenção de magoar ou vilipendiar a estudante ou seus colegas. Peço, assim minhas mais sinceras e profundas desculpas a aluna por tê-la ferido em sua dignidade humana.
 Aprendi com esse episódio lição de vida muito importante sobre ética e humanidade entendendo que tal procedimento não pode e não será repetido jamais, integrando assim esse ensinamento ao convívio decente e digno para com alunos e alunas em minha prática docente se houver. Bem como lição essa importante para nortear minhas futuras relações pessoais e profissionais

Respeitosamente
Joel Barbujiani Sigolo