= Repasse da Câmara de Avaliações e Normas (CAN) da USP sobre os campos
// :page-subtitle:
:page-identificador: 20240406_repasse_can_usp_campos
:page-data: "06 de abril de 2024"
:page-layout: boletim_post
:page-categories: [boletim_post]
:page-tags: []
:page-autoria: 'Thiago Viana (Progídio)'
:page-autoria-completa: 'Thiago Viana (Progídio), presidente do CEPEGE'
:page-resumo: ['Repasse do representante discente na CAN sobre a estratégia da USP para o corte dos trabalhos de campos.']

[.aviso-amarelo]
--
Publicado no Boletim do CEPEGE em 13 de março de 2024.
--

Como alguns do IGc já sabem, sou Representante Discente da CoG (Conselho de Graduação) da USP e da CAN (Câmara de Avaliação e Normas).

Mas o que é a CAN? A CAN se trata de uma câmara submetida ao Conselho de Graduação voltado - a como diz o nome - à construção de normativas(inclusive de trabalhos de campo, regimentos internos de unidades) e avaliações(tais como pedidos de viagens didáticas não estruturantes).

A reunião de Novembro foi a que passou a atual Normativa de Viagens Didáticas. Como alguns já sabem, essa normativa define que viagens não-estruturantes (viagens sem as quais, ainda é possível se formar, distinguindo-se das indispensáveis viagens estruturantes) não operam em dias de recesso e define que todo o dinheiro de viagens estruturantes deve estar contido no pedido original para a Dotação Orçamentária Básica. É preciso questionar a necessidade de se distinguir entre estruturais e não-estruturais, classificação feita com o objetivo de saber o que cortar de forma mais “tolerável”(nunca sendo minimamente debatido a expansão do orçamento de campos ou das diárias).

A reunião foi regada a “conversas de bar” e “piadocas” do tipo “Não consigo nem mais almoçar com tanta solicitação de campo” ou “Botou ‘Vide ementa’ na solicitação, rejeitado! GAME OVER!”. Na última reunião, entre outras coisas, destaco que foi passado um Novo Regimento do CCM(curso de ciências moleculares), que aparentemente seriam pequenas mudanças burocráticas - segundo professores. Sobre as Viagens Didáticas é importante ressaltar que a atual reitoria e a CAN não definiram nada a respeito das estruturantes de cada unidade e consideram que o Ofício do IGc (pedindo que aulas de campo estruturantes pudessem ser realizadas em período de recesso) não contradizem a Normativa, dado que ela lida com viagens não estruturantes.

A forma explicitamente antidemocrática como esses órgãos funcionam, especialmente nos âmbitos superiores, demonstram a verdadeira face da Universidade a serviço do capital e do projeto da burguesia dependente para o país (projeto este que não precisa de universidades de ponta). Esse projeto, nesse ambiente mais “escondido” de outros, demonstra seu expresso repúdio ao espírito democrático que tanto proclamam defender.

Precisa-se ter a compreensão de que esses processos de desmonte da universidade não ocorrem à toa e não ocorrem apenas na USP. Em várias universidades, em especial nas federais, esse projeto está bem avançado. Todo esse processo que está sendo descrito é controlado pelos interesses da classe dominante. Especialmente em uma era transnacionalizada e neoliberal da economia mundial, o papel do Brasil na cadeia do capitalismo mundial é de cada vez mais ser apenas exclusivamente um exportador de commodities, com mão de obra barata - daí todo o discurso ideológico sobre o excesso de petrologia e mapeamento.

Enquanto não compreendermos como as questões imediatas que vemos na universidade e as suas relações de poder refletem estruturas de poder para fora da universidade; enquanto não compreendermos mais profundamente o papel da universidade em uma sociedade de capitalismo dependente, o nosso movimento estará bem limitado. Não adianta reivindicar uma universidade pública, se ela permanece sendo uma afinca serva dos interesses do capital financeiro. A Universidade deve servir aos interesses de quem contribui para sua existência e funcionamento, ela deve ser uma Universidade Popular.